spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul
#        username: root
#        password: 1234
        url: jdbc:mysql://awseb-e-pmnp8rfpvm-stack-awsebrdsdatabase-nacnh6a661dq.ctg6im4ygs38.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul
        username: fastcam
        password: fastcam1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
